[package]
name = "paradencer-config"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
toml.workspace = true
serde.workspace = true
tracing.workspace = true
serde_json.workspace = true
paradencer-core = { path = "../paradencer-core" }
paradencer-execution = { path = "../paradencer-execution" }
paradencer-net = { path = "../paradencer-net" }
paradencer-stages = { path = "../paradencer-stages" }
paradencer-storage = { path = "../paradencer-storage" }
