[package]
name = "paradencer-ingress"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
paradencer-constants.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["net", "sync", "time"] }
quinn.workspace = true
rustls.workspace = true
bytes.workspace = true
rcgen.workspace = true
ed25519-dalek.workspace = true
sha2.workspace = true
parking_lot.workspace = true
crossbeam-channel.workspace = true
tracing.workspace = true
