[package]
name = "karstflow-config"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
toml.workspace = true
serde.workspace = true
tracing.workspace = true
serde_json.workspace = true
karstflow-constants = { workspace = true }
karstflow-core = { workspace = true }
karstflow-execution = { workspace = true }
karstflow-net = { workspace = true }
karstflow-stages = { workspace = true }
karstflow-storage = { workspace = true }
