[package]
name = "paradencer-control"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
paradencer-config = { path = "../paradencer-config" }
paradencer-consensus = { path = "../paradencer-consensus" }
paradencer-core = { path = "../paradencer-core" }
paradencer-execution = { path = "../paradencer-execution" }
paradencer-mesh = { path = "../paradencer-mesh" }
paradencer-net = { path = "../paradencer-net" }
paradencer-runtime = { path = "../paradencer-runtime" }
paradencer-stages = { path = "../paradencer-stages" }
paradencer-storage = { path = "../paradencer-storage" }
paradencer-topology = { path = "../paradencer-topology" }
paradencer-types = { path = "../paradencer-types" }

paradencer-observability = { path = "../paradencer-observability" }
paradencer-rpc = { path = "../paradencer-rpc" }
tokio = { workspace = true, features = ["sync", "rt", "time"] }
