[package]
name = "paradencer-node"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
crossbeam-channel.workspace = true
ed25519-dalek.workspace = true
tracing.workspace = true
paradencer-consensus = { path = "../paradencer-consensus" }
paradencer-control = { path = "../paradencer-control" }
paradencer-config = { path = "../paradencer-config" }
paradencer-mesh = { path = "../paradencer-mesh" }
paradencer-net = { path = "../paradencer-net" }
paradencer-observability = { path = "../paradencer-observability" }
paradencer-plugin = { path = "../paradencer-plugin" }
paradencer-stages = { path = "../paradencer-stages" }
paradencer-storage = { path = "../paradencer-storage" }
paradencer-topology = { path = "../paradencer-topology" }
paradencer-types = { path = "../paradencer-types" }
