[package]
name = "paradencer-node"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
crossbeam-channel.workspace = true
tracing.workspace = true
paradencer-control = { path = "../paradencer-control" }
paradencer-config = { path = "../paradencer-config" }
paradencer-net = { path = "../paradencer-net" }
paradencer-plugin = { path = "../paradencer-plugin" }
paradencer-stages = { path = "../paradencer-stages" }
paradencer-topology = { path = "../paradencer-topology" }
