[package]
name = "paradencer-node"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
paradencer-control = { path = "../paradencer-control" }
paradencer-config = { path = "../paradencer-config" }
paradencer-stages = { path = "../paradencer-stages" }
paradencer-topology = { path = "../paradencer-topology" }
