[package]
name = "karstflow-consensus"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
karstflow-constants = { path = "../karstflow-constants" }
karstflow-crypto = { path = "../karstflow-crypto" }
karstflow-storage = { path = "../karstflow-storage" }
karstflow-types = { path = "../karstflow-types" }
karstflow-ids = { path = "../karstflow-ids" }
karstflow-mesh = { path = "../karstflow-mesh" }
bincode = { workspace = true }
ed25519-dalek = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
