[package]
name = "paradencer-plugin"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
libloading.workspace = true
crossbeam-channel.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
