[package]
name = "karstflow-stages"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
bincode.workspace = true
karstflow-consensus = { workspace = true }
karstflow-net = { workspace = true }
karstflow-execution = { workspace = true }
karstflow-storage = { workspace = true }
karstflow-runtime = { workspace = true }
karstflow-mesh = { workspace = true }
karstflow-types = { workspace = true }
karstflow-crypto = { workspace = true }
karstflow-sbpf = { workspace = true }
karstflow-constants = { workspace = true }
karstflow-ids = { workspace = true }
crossbeam-channel = { workspace = true }
tracing.workspace = true
reed-solomon-erasure = "6.0"
ed25519-dalek = { version = "2.1", features = ["rand_core"] }
blake3.workspace = true
bs58.workspace = true
sha2.workspace = true

[dev-dependencies]
rand = "0.8"
