[package]
name = "karstflow-control"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
crossbeam-channel = { workspace = true }
karstflow-config = { workspace = true }
karstflow-consensus = { workspace = true }
karstflow-constants = { workspace = true }
karstflow-crypto = { workspace = true }
karstflow-core = { workspace = true }
karstflow-execution = { workspace = true }
karstflow-ids = { workspace = true }
karstflow-mesh = { workspace = true }
karstflow-net = { workspace = true }
karstflow-runtime = { workspace = true }
karstflow-stages = { workspace = true }
karstflow-storage = { workspace = true }
karstflow-topology = { workspace = true }
karstflow-types = { workspace = true }

karstflow-observability = { workspace = true }
karstflow-rpc = { workspace = true }
libc = "0.2"
bs58.workspace = true
serde_json.workspace = true
parking_lot.workspace = true
tokio = { workspace = true, features = ["sync", "rt", "time"] }
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
