#[derive(serde::Serialize)]
pub(crate) struct IngressFilterMetrics {
    pub(crate) accepted_transactions: u64,
    pub(crate) accepted_quic_source: u64,
    pub(crate) accepted_gossip_source: u64,
    pub(crate) accepted_bundle_source: u64,
    pub(crate) accepted_rpc_source: u64,
    pub(crate) duplicate_transactions: u64,
    pub(crate) duplicate_quic_source: u64,
    pub(crate) duplicate_gossip_source: u64,
    pub(crate) duplicate_bundle_source: u64,
    pub(crate) duplicate_rpc_source: u64,
    pub(crate) dropped_empty_payload: u64,
    pub(crate) dropped_oversized_payload: u64,
    pub(crate) dropped_disallowed_source: u64,
    pub(crate) dropped_rate_limited_source: u64,
    pub(crate) dropped_cost_budget_source: u64,
    pub(crate) dropped_downstream_backpressure: u64,
}

#[derive(serde::Serialize)]
pub(crate) struct ShredFilterMetrics {
    pub(crate) accepted_shreds: u64,
    pub(crate) duplicate_shreds: u64,
    pub(crate) dropped_empty_payload: u64,
    pub(crate) dropped_oversized_payload: u64,
    pub(crate) dropped_disallowed_source: u64,
}

#[derive(serde::Serialize)]
pub(crate) struct BlockAssemblyMetrics {
    pub(crate) deferred_retries: u64,
    pub(crate) dropped_fragments: u64,
    pub(crate) committed_fragments: u64,
    pub(crate) pending_retries: u64,
    pub(crate) execution_error_total: u64,
    pub(crate) execution_error_empty_batch: u64,
    pub(crate) execution_error_cost_overflow: u64,
    pub(crate) execution_error_adapter_apply: u64,
    pub(crate) execution_error_adapter_rollback: u64,
    pub(crate) execution_error_adapter_state_conflict: u64,
    pub(crate) execution_error_adapter_contract_violation: u64,
    pub(crate) execution_error_adapter_receipt_missing: u64,
    pub(crate) execution_error_adapter_mutex_poisoned: u64,
    pub(crate) execution_error_fail_open_continue: u64,
    pub(crate) execution_error_fail_fast_halt: u64,
    pub(crate) execution_error_fail_open_circuit_breaker_halt: u64,
    pub(crate) execution_error_consecutive_current: u64,
    pub(crate) retry_scheduled_replay_conflict: u64,
    pub(crate) retry_scheduled_transient_pressure: u64,
    pub(crate) retry_scheduled_resource_exhaustion: u64,
    pub(crate) retry_scheduled_fallback: u64,
    pub(crate) dropped_replay_conflict: u64,
    pub(crate) dropped_deterministic: u64,
    pub(crate) dropped_transient_pressure: u64,
    pub(crate) dropped_resource_exhaustion: u64,
    pub(crate) dropped_fallback: u64,
    pub(crate) dropped_reorg_retry_exhausted: u64,
    pub(crate) leader_gate_permit: u64,
    pub(crate) leader_gate_hold: u64,
    pub(crate) fork_choice_keep: u64,
    pub(crate) fork_choice_reorg: u64,
    pub(crate) execution_health_cooldown_entries: u64,
    pub(crate) execution_health_cooldown_skipped_ticks: u64,
    pub(crate) replay_safety_hold_entries: u64,
    pub(crate) replay_safety_hold_skipped_ticks: u64,
    pub(crate) fork_choice_quarantine_entries: u64,
    pub(crate) fork_choice_quarantine_skipped_ticks: u64,
    pub(crate) slot_transition_committed: u64,
    pub(crate) slot_transition_dropped: u64,
    pub(crate) slot_transition_reorg_pending: u64,
    pub(crate) replay_controller_holds: u64,
    pub(crate) replay_controller_confirmed_candidates: u64,
    pub(crate) replay_controller_candidate_switches: u64,
    pub(crate) replay_controller_stale_candidates_pruned: u64,
    pub(crate) replay_controller_switch_suppressed: u64,
    pub(crate) replay_controller_active_candidate_failed_ratio_bps: u64,
    pub(crate) replay_controller_tracked_candidates: u64,
    pub(crate) replay_window_checkpoint_depth: u64,
    pub(crate) replay_window_rewinds: u64,
    pub(crate) replay_window_catalog_snapshots_pruned: u64,
    pub(crate) execution_state_rewind_failures: u64,
}
