[package]
name = "paradencer-stages"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
bincode.workspace = true
paradencer-consensus = { path = "../paradencer-consensus" }
paradencer-ingress = { path = "../paradencer-ingress" }
paradencer-execution = { path = "../paradencer-execution" }
paradencer-storage = { path = "../paradencer-storage" }
paradencer-runtime = { path = "../paradencer-runtime" }
paradencer-mesh = { path = "../paradencer-mesh" }
paradencer-types = { path = "../paradencer-types" }
paradencer-crypto = { path = "../paradencer-crypto" }
paradencer-sbpf = { path = "../paradencer-sbpf" }
paradencer-constants = { path = "../paradencer-constants" }
reed-solomon-erasure = "6.0"
ed25519-dalek = { version = "2.1", features = ["rand_core"] }
blake3.workspace = true

[dev-dependencies]
rand = "0.8"
paradencer-ids = { path = "../paradencer-ids" }
