[package]
name = "karstflow-execution"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
karstflow-storage = { workspace = true }
karstflow-consensus = { workspace = true }
karstflow-sbpf = { workspace = true }
karstflow-types = { workspace = true }
dashmap = "6.1"

[dev-dependencies]
karstflow-ids = { workspace = true }
