[package]
name = "karstflow-node"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
crossbeam-channel.workspace = true
ed25519-dalek.workspace = true
tracing.workspace = true
karstflow-consensus = { workspace = true }
karstflow-constants = { workspace = true }
karstflow-control = { workspace = true }
karstflow-config = { workspace = true }
karstflow-mesh = { workspace = true }
karstflow-net = { workspace = true }
karstflow-observability = { workspace = true }
karstflow-plugin = { workspace = true }
karstflow-stages = { workspace = true }
karstflow-storage = { workspace = true }
karstflow-topology = { workspace = true }
karstflow-types = { workspace = true }
