[package]
name = "paradencer-topology"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
toml.workspace = true
crossbeam-channel = { workspace = true }
paradencer-core = { path = "../paradencer-core" }
paradencer-net = { path = "../paradencer-net" }
paradencer-runtime = { path = "../paradencer-runtime" }
paradencer-stages = { path = "../paradencer-stages" }
paradencer-storage = { path = "../paradencer-storage" }
paradencer-mesh = { path = "../paradencer-mesh" }
paradencer-types = { path = "../paradencer-types" }
paradencer-constants = { path = "../paradencer-constants" }
