[package]
name = "karstflow-topology"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
toml.workspace = true
crossbeam-channel = { workspace = true }
karstflow-core = { workspace = true }
karstflow-net = { workspace = true }
karstflow-runtime = { workspace = true }
karstflow-stages = { workspace = true }
karstflow-storage = { workspace = true }
karstflow-mesh = { workspace = true }
karstflow-types = { workspace = true }
karstflow-constants = { workspace = true }
