/// eBPF XDP program generator for packet steering.
///
/// Generates eBPF bytecode that redirects matching UDP packets to AF_XDP
/// sockets via XSKMAP. The program checks:
///   1. Ethernet type == IPv4 (0x0800)
///   2. IP protocol == UDP (17)
///   3. Optionally: destination IP matches a filter
///   4. UDP destination port matches one of the configured ports
///
/// Matching packets get `XDP_REDIRECT` to the XSKMAP (keyed by NIC RX
/// queue index). Non-matching packets pass through to the kernel stack.
///
/// The generated bytecode is platform-independent. Actual BPF syscalls
/// for loading and attaching the program are Linux-only.
use paradencer_constants::network::{
    BPF_FUNC_REDIRECT_MAP, BPF_MAX_INSNS, XDP_MAX_FILTER_PORTS, XDP_PASS,
};

/// A single 64-bit eBPF instruction.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(C)]
pub struct BpfInsn {
    /// Opcode (8 bits).
    pub code: u8,
    /// Source/destination register nibbles (dst:4 | src:4).
    pub regs: u8,
    /// Signed offset (16 bits).
    pub off: i16,
    /// Signed immediate (32 bits).
    pub imm: i32,
}

impl BpfInsn {
    const fn new(code: u8, dst: u8, src: u8, off: i16, imm: i32) -> Self {
        Self {
            code,
            regs: (src << 4) | (dst & 0x0F),
            off,
            imm,
        }
    }
}

// eBPF instruction encoding helpers.

/// ALU64 immediate: dst = imm
const fn mov64_imm(dst: u8, imm: i32) -> BpfInsn {
    BpfInsn::new(0xb7, dst, 0, 0, imm)
}

/// ALU64 register: dst = src
const fn mov64_reg(dst: u8, src: u8) -> BpfInsn {
    BpfInsn::new(0xbf, dst, src, 0, 0)
}

/// ALU64 immediate: dst += imm
const fn add64_imm(dst: u8, imm: i32) -> BpfInsn {
    BpfInsn::new(0x07, dst, 0, 0, imm)
}

/// Load byte from memory: dst = *(u8 *)(src + off)
const fn ldxb(dst: u8, src: u8, off: i16) -> BpfInsn {
    BpfInsn::new(0x71, dst, src, off, 0)
}

/// Load half-word from memory: dst = *(u16 *)(src + off)
const fn ldxh(dst: u8, src: u8, off: i16) -> BpfInsn {
    BpfInsn::new(0x69, dst, src, off, 0)
}

/// Load word from memory: dst = *(u32 *)(src + off)
const fn ldxw(dst: u8, src: u8, off: i16) -> BpfInsn {
    BpfInsn::new(0x61, dst, src, off, 0)
}

/// Load 64-bit immediate (two instructions): dst = imm64
/// First instruction has the low 32 bits, second has the high 32 bits.
fn lddw(dst: u8, imm64: u64) -> [BpfInsn; 2] {
    [
        BpfInsn::new(0x18, dst, 0, 0, imm64 as i32),
        BpfInsn::new(0x00, 0, 0, 0, (imm64 >> 32) as i32),
    ]
}

/// Jump always: goto pc + off
#[allow(dead_code)]
const fn ja(off: i16) -> BpfInsn {
    BpfInsn::new(0x05, 0, 0, off, 0)
}

/// Jump if equal immediate: if dst == imm goto pc + off
const fn jeq_imm(dst: u8, imm: i32, off: i16) -> BpfInsn {
    BpfInsn::new(0x15, dst, 0, off, imm)
}

/// Jump if not equal immediate: if dst != imm goto pc + off
const fn jne_imm(dst: u8, imm: i32, off: i16) -> BpfInsn {
    BpfInsn::new(0x55, dst, 0, off, imm)
}

/// Jump if greater than (unsigned) register: if dst > src goto pc + off
const fn jgt_reg(dst: u8, src: u8, off: i16) -> BpfInsn {
    BpfInsn::new(0x2d, dst, src, off, 0)
}

/// Call BPF helper function
const fn call(func_id: u32) -> BpfInsn {
    BpfInsn::new(0x85, 0, 0, 0, func_id as i32)
}

/// Exit program (return r0)
const fn exit() -> BpfInsn {
    BpfInsn::new(0x95, 0, 0, 0, 0)
}

/// Configuration for XDP program generation.
#[derive(Debug, Clone)]
pub struct XdpFilterConfig {
    /// XSKMAP file descriptor (set after map creation).
    pub xsk_map_fd: i32,
    /// Optional IPv4 destination filter (0 = no filter, accept any IP).
    pub listen_ip4_addr: u32,
    /// UDP ports to redirect to AF_XDP.
    pub ports: Vec<u16>,
}

impl XdpFilterConfig {
    /// Create a new filter config with the given ports.
    pub fn new(ports: &[u16]) -> Self {
        Self {
            xsk_map_fd: -1,
            listen_ip4_addr: 0,
            ports: ports.to_vec(),
        }
    }
}

/// Result of program generation.
pub struct GeneratedProgram {
    /// eBPF instruction buffer.
    pub instructions: Vec<BpfInsn>,
    /// Number of instructions.
    pub insn_count: usize,
}

impl GeneratedProgram {
    /// Get the raw instruction bytes for loading via BPF syscall.
    pub fn as_bytes(&self) -> &[u8] {
        let ptr = self.instructions.as_ptr() as *const u8;
        let len = self.insn_count * std::mem::size_of::<BpfInsn>();
        unsafe { std::slice::from_raw_parts(ptr, len) }
    }
}

/// Generate an XDP eBPF program for packet steering.
///
/// The generated program:
/// 1. Validates Ethernet header (type == IPv4)
/// 2. Validates IPv4 header (protocol == UDP)
/// 3. Optionally checks destination IP
/// 4. Checks UDP destination port against the port list
/// 5. Matching packets: XDP_REDIRECT via XSKMAP
/// 6. Non-matching packets: XDP_PASS to kernel
///
/// Returns the generated program or `None` if the config is invalid.
pub fn generate_xdp_program(config: &XdpFilterConfig) -> Option<GeneratedProgram> {
    if config.ports.is_empty() || config.ports.len() > XDP_MAX_FILTER_PORTS {
        return None;
    }

    let mut insns: Vec<BpfInsn> = Vec::with_capacity(BPF_MAX_INSNS);

    // Register usage:
    // r1 = xdp_md context pointer (input)
    // r2 = packet data start
    // r3 = packet data end
    // r4 = current offset / scratch
    // r6 = saved context pointer

    // Save context pointer.
    insns.push(mov64_reg(6, 1)); // r6 = r1 (save xdp_md)

    // Load packet pointers from xdp_md.
    insns.push(ldxw(2, 1, 0)); // r2 = xdp_md->data
    insns.push(ldxw(3, 1, 4)); // r3 = xdp_md->data_end

    // --- Ethernet header check (14 bytes) ---
    // Bounds check: need at least 14 bytes.
    insns.push(mov64_reg(4, 2)); // r4 = data
    insns.push(add64_imm(4, 14)); // r4 = data + 14

    // We'll fill in the XDP_PASS jump offset later.
    let pass_label_start = insns.len();
    insns.push(jgt_reg(4, 3, 0)); // if r4 > data_end goto PASS (placeholder)

    // Check EtherType == 0x0800 (IPv4). EtherType at offset 12, big-endian.
    insns.push(ldxh(4, 2, 12)); // r4 = *(u16*)(data + 12)
    insns.push(jne_imm(4, 0x0008, 0)); // if r4 != 0x0008 goto PASS (network byte order on LE)
    let pass_label_eth = insns.len() - 1;

    // --- IPv4 header check ---
    // Minimum 20 bytes starting at offset 14.
    insns.push(mov64_reg(4, 2)); // r4 = data
    insns.push(add64_imm(4, 14 + 20)); // r4 = data + 34
    insns.push(jgt_reg(4, 3, 0)); // if r4 > data_end goto PASS
    let pass_label_ip = insns.len() - 1;

    // Get IP header length from first byte (IHL field, lower nibble * 4).
    insns.push(ldxb(4, 2, 14)); // r4 = *(u8*)(data + 14) [version+IHL]
                                // We need the IHL field (lower 4 bits) * 4 for variable-length IP headers.
                                // For simplicity, check protocol at fixed offset 23 (byte 9 of IP header).
                                // Protocol field is at IP header offset 9 = data offset 23.
    insns.push(ldxb(4, 2, 23)); // r4 = *(u8*)(data + 23) [protocol]
    insns.push(jne_imm(4, 17, 0)); // if r4 != 17 (UDP) goto PASS
    let pass_label_proto = insns.len() - 1;

    // --- Optional destination IP check ---
    let pass_label_ip_filter = if config.listen_ip4_addr != 0 {
        // Destination IP at offset 30 (IP header offset 16).
        insns.push(ldxw(4, 2, 30)); // r4 = *(u32*)(data + 30) [dst IP, network order]
        let ip_ne = config.listen_ip4_addr.to_be() as i32;
        insns.push(jne_imm(4, ip_ne, 0)); // if r4 != listen_ip goto PASS
        Some(insns.len() - 1)
    } else {
        None
    };

    // --- UDP header check ---
    // UDP starts at offset 34 (assuming no IP options). Need 8 bytes.
    insns.push(mov64_reg(4, 2)); // r4 = data
    insns.push(add64_imm(4, 34 + 8)); // r4 = data + 42
    insns.push(jgt_reg(4, 3, 0)); // if r4 > data_end goto PASS
    let pass_label_udp = insns.len() - 1;

    // Load UDP destination port (offset 36, 2 bytes, network byte order).
    insns.push(ldxh(4, 2, 36)); // r4 = *(u16*)(data + 36) [dst port]

    // --- Port matching ---
    // Compare against each configured port.
    let mut port_pass_labels = Vec::new();
    for (i, &port) in config.ports.iter().enumerate() {
        let port_ne = port.to_be() as i32;
        if i == config.ports.len() - 1 {
            // Last port: if no match, fall through to PASS.
            insns.push(jne_imm(4, port_ne, 0)); // goto PASS
            port_pass_labels.push(insns.len() - 1);
        } else {
            // If match, jump to REDIRECT.
            insns.push(jeq_imm(4, port_ne, 0)); // goto REDIRECT (placeholder)
            port_pass_labels.push(insns.len() - 1);
        }
    }

    // --- REDIRECT block ---
    let redirect_pc = insns.len();

    // r2 = xdp_md->rx_queue_index (offset 16 in xdp_md).
    insns.push(ldxw(2, 6, 16)); // r2 = rx_queue_index

    // r1 = XSKMAP fd (64-bit immediate via lddw).
    let lddw_insns = lddw(1, config.xsk_map_fd as u64);
    insns.push(lddw_insns[0]);
    insns.push(lddw_insns[1]);

    insns.push(mov64_imm(3, 0)); // r3 = flags = 0
    insns.push(call(BPF_FUNC_REDIRECT_MAP)); // r0 = bpf_redirect_map(r1, r2, r3)
    insns.push(exit()); // return r0

    // --- PASS block ---
    let pass_pc = insns.len();
    insns.push(mov64_imm(0, XDP_PASS as i32)); // r0 = XDP_PASS
    insns.push(exit()); // return r0

    // --- Patch jump offsets ---
    // All "goto PASS" jumps.
    let pass_targets = [
        pass_label_start,
        pass_label_eth,
        pass_label_ip,
        pass_label_proto,
        pass_label_udp,
    ];
    for &idx in &pass_targets {
        let offset = (pass_pc as i16) - (idx as i16) - 1;
        insns[idx].off = offset;
    }
    if let Some(idx) = pass_label_ip_filter {
        let offset = (pass_pc as i16) - (idx as i16) - 1;
        insns[idx].off = offset;
    }

    // Port labels: all but last are "goto REDIRECT on match", last is "goto PASS on no match".
    for (i, &idx) in port_pass_labels.iter().enumerate() {
        if i == config.ports.len() - 1 {
            // Last one: jne → PASS.
            let offset = (pass_pc as i16) - (idx as i16) - 1;
            insns[idx].off = offset;
        } else {
            // Others: jeq → REDIRECT.
            let offset = (redirect_pc as i16) - (idx as i16) - 1;
            insns[idx].off = offset;
        }
    }

    let insn_count = insns.len();
    Some(GeneratedProgram {
        instructions: insns,
        insn_count,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bpf_insn_size() {
        assert_eq!(std::mem::size_of::<BpfInsn>(), 8);
    }

    #[test]
    fn generate_single_port() {
        let config = XdpFilterConfig {
            xsk_map_fd: 42,
            listen_ip4_addr: 0,
            ports: vec![8000],
        };
        let prog = generate_xdp_program(&config).unwrap();
        assert!(prog.insn_count > 0);
        assert!(prog.insn_count < BPF_MAX_INSNS);

        // Last instruction should be exit.
        assert_eq!(prog.instructions[prog.insn_count - 1].code, 0x95);
    }

    #[test]
    fn generate_multiple_ports() {
        let config = XdpFilterConfig {
            xsk_map_fd: 10,
            listen_ip4_addr: 0,
            ports: vec![8000, 8001, 8002, 8003],
        };
        let prog = generate_xdp_program(&config).unwrap();
        assert!(prog.insn_count > 0);

        // Should have one more instruction per extra port.
        let single = generate_xdp_program(&XdpFilterConfig {
            ports: vec![8000],
            ..config.clone()
        })
        .unwrap();
        assert!(prog.insn_count > single.insn_count);
    }

    #[test]
    fn generate_with_ip_filter() {
        let config = XdpFilterConfig {
            xsk_map_fd: 5,
            listen_ip4_addr: 0x0A000001, // 10.0.0.1
            ports: vec![9000],
        };
        let prog = generate_xdp_program(&config).unwrap();
        assert!(prog.insn_count > 0);

        // Should have more instructions than without IP filter.
        let no_filter = generate_xdp_program(&XdpFilterConfig {
            listen_ip4_addr: 0,
            ..config.clone()
        })
        .unwrap();
        assert!(prog.insn_count > no_filter.insn_count);
    }

    #[test]
    fn reject_empty_ports() {
        let config = XdpFilterConfig {
            xsk_map_fd: 1,
            listen_ip4_addr: 0,
            ports: vec![],
        };
        assert!(generate_xdp_program(&config).is_none());
    }

    #[test]
    fn reject_too_many_ports() {
        let config = XdpFilterConfig {
            xsk_map_fd: 1,
            listen_ip4_addr: 0,
            ports: (0..=XDP_MAX_FILTER_PORTS as u16).collect(),
        };
        assert!(generate_xdp_program(&config).is_none());
    }

    #[test]
    fn as_bytes_length() {
        let config = XdpFilterConfig {
            xsk_map_fd: 1,
            listen_ip4_addr: 0,
            ports: vec![8000],
        };
        let prog = generate_xdp_program(&config).unwrap();
        assert_eq!(prog.as_bytes().len(), prog.insn_count * 8);
    }

    #[test]
    fn program_ends_with_pass_exit() {
        let config = XdpFilterConfig {
            xsk_map_fd: 1,
            listen_ip4_addr: 0,
            ports: vec![8000],
        };
        let prog = generate_xdp_program(&config).unwrap();
        let n = prog.insn_count;

        // Last two instructions: mov r0, XDP_PASS; exit
        assert_eq!(prog.instructions[n - 2].code, 0xb7); // mov64_imm
        assert_eq!(prog.instructions[n - 2].imm, XDP_PASS as i32);
        assert_eq!(prog.instructions[n - 1].code, 0x95); // exit
    }

    #[test]
    fn program_has_redirect_section() {
        let config = XdpFilterConfig {
            xsk_map_fd: 42,
            listen_ip4_addr: 0,
            ports: vec![8000],
        };
        let prog = generate_xdp_program(&config).unwrap();

        // Should contain a call to bpf_redirect_map.
        let has_call = prog
            .instructions
            .iter()
            .any(|i| i.code == 0x85 && i.imm == BPF_FUNC_REDIRECT_MAP as i32);
        assert!(has_call);
    }

    #[test]
    fn jump_offsets_are_valid() {
        let config = XdpFilterConfig {
            xsk_map_fd: 1,
            listen_ip4_addr: 0x0A000001,
            ports: vec![8000, 9000],
        };
        let prog = generate_xdp_program(&config).unwrap();

        // Verify all jump instructions have valid offsets.
        for (i, insn) in prog.instructions.iter().enumerate() {
            let is_jump = (insn.code & 0x07) == 0x05 && insn.code != 0x85; // jump class, not call
            if is_jump {
                let target = i as i32 + 1 + insn.off as i32;
                assert!(
                    target >= 0 && (target as usize) <= prog.insn_count,
                    "invalid jump at insn {i}: offset {} targets {target} (max {})",
                    insn.off,
                    prog.insn_count
                );
            }
        }
    }
}
